# Generated by Django 5.1.6 on 2025-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12),
        ),
    ]
