# Generated by Django 5.1.6 on 2025-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0003_alter_skill_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_me_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
