# Generated by Django 5.1.6 on 2025-03-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0004_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='title',
        ),
    ]
